# elasticsearch/config/elasticsearch.yml
cluster.name: security-monitoring-cluster
node.name: es-node-01
network.host: 0.0.0.0
http.port: 9200

# Memory (ปรับตามเครื่อง)
bootstrap.memory_lock: true
# ตั้งใน docker-compose: ES_JAVA_OPTS=-Xms2g -Xmx2g

# Performance
indices.memory.index_buffer_size: 20%
thread_pool.write.queue_size: 1000

# --- CORS Settings ---
http.cors.enabled: true
http.cors.allow-origin: "http://localhost:5173"
http.cors.allow-credentials: true
http.cors.allow-methods: OPTIONS, POST, GET
http.cors.allow-headers: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Access-Control-Allow-Headers, Accept
