input {
  beats {
    port => 5044
  }
}

filter {
  if [winlog][channel] == "Security" and [event_id] == 4624 {
    mutate {
      add_field => {
        "attack.tactic" => "Initial Access"
        "attack.technique" => "Valid Accounts (T1078)"
      }
    }
  }

  if [winlog][channel] == "Microsoft-Windows-Sysmon/Operational" and [event_id] == 1 {
    mutate {
      add_field => {
        "attack.tactic" => "Execution"
        "attack.technique" => "Process Creation (T1059)"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "winlogbeat-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
